version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "8080:80"  # Map frontend's port 80 to host's port 80
    depends_on:
      - image_recognition

  image_recognition:
    container_name: image_recognition
    build:
      context: .
    volumes:
      - ./shared:/app/shared:ro
